# Generated by Django 3.1.7 on 2021-03-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('video_id', models.CharField(max_length=120, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('stado', models.CharField(choices=[('PU', 'Publish'), ('DR', 'Draft')], default='DR', max_length=2)),
                ('tiempo_publicado', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProxiTodoLosVideo',
            fields=[
            ],
            options={
                'verbose_name': 'Todo los Video',
                'verbose_name_plural': 'Todos los Publicados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Video.video',),
        ),
        migrations.CreateModel(
            name='VideoPublicadoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Video Publicado',
                'verbose_name_plural': 'Videos Publicados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Video.video',),
        ),
    ]
