# Generated by Django 3.1.7 on 2021-05-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20210501_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='relacionados',
            field=models.ManyToManyField(blank=True, null=True, related_name='_playlist_relacionados_+', through='playlist.PlayListRelacionado', to='playlist.PlayList'),
        ),
    ]
