# Generated by Django 3.1.7 on 2021-03-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20210326_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVShowProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Tv Show',
                'verbose_name_plural': 'Tv Shows',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('playlist.playlist',),
        ),
        migrations.CreateModel(
            name='TVShowTemporadaProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Tv Show Temporada',
                'verbose_name_plural': 'Tv Shows Temporadas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('playlist.playlist',),
        ),
    ]
