# Generated by Django 3.1.7 on 2021-03-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_playlist_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Pelicula',
                'verbose_name_plural': 'Peliculas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('playlist.playlist',),
        ),
    ]
