# Generated by Django 3.1.7 on 2021-03-29 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('playlist', '0006_playlist_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist', to='categoria.categoria'),
        ),
    ]
